// examples/demo-no-location/src/App.tsx
import OneSignal, { LogLevel } from '@onesignal/capacitor-plugin';
import { useCallback, useEffect, useState } from 'react';

const ONESIGNAL_APP_ID = import.meta.env.VITE_ONESIGNAL_APP_ID?.trim() || 'your-onesignal-app-id';

const isPlaceholder = (value: string): boolean => value.toLowerCase().startsWith('your-');

export default function App() {
  const [permission, setPermission] = useState<boolean | null>(null);
  const [pushSubscriptionId, setPushSubscriptionId] = useState<string | null>(null);
  const [requestingPermission, setRequestingPermission] = useState(false);
  const [sending, setSending] = useState(false);

  const refreshPushState = useCallback(() => {
    void OneSignal.Notifications.hasPermission()
      .then(setPermission)
      .catch(() => setPermission(null));

    void OneSignal.User.pushSubscription
      .getIdAsync()
      .then(setPushSubscriptionId)
      .catch(() => setPushSubscriptionId(null));
  }, []);

  useEffect(() => {
    OneSignal.Debug.setLogLevel(LogLevel.Verbose);
    void OneSignal.initialize(ONESIGNAL_APP_ID);
    refreshPushState();
  }, [refreshPushState]);

  const requestPermission = useCallback(async () => {
    setRequestingPermission(true);
    try {
      const granted = await OneSignal.Notifications.requestPermission(false);
      setPermission(granted);
      refreshPushState();
    } catch (error) {
      window.alert(`Permission Request Failed\n\n${String(error)}`);
    } finally {
      setRequestingPermission(false);
    }
  }, [refreshPushState]);

  const testLocationPermissionRequest = useCallback(async () => {
    try {
      await OneSignal.Location.requestPermission();
    } catch (error) {
      console.error('OneSignal.Location.requestPermission failed:', error);
    }
  }, []);

  const sendTestNotification = useCallback(async () => {
    if (isPlaceholder(ONESIGNAL_APP_ID)) {
      window.alert(
        'Configure OneSignal\n\nSet VITE_ONESIGNAL_APP_ID in .env before sending a test push.',
      );
      return;
    }

    if (!permission) {
      window.alert(
        'Notifications Disabled\n\nRequest notification permission before sending a test push.',
      );
      return;
    }

    if (!pushSubscriptionId) {
      window.alert('No Push Subscription\n\nAllow notifications, then wait for a push ID.');
      return;
    }

    setSending(true);
    try {
      const response = await fetch('https://onesignal.com/api/v1/notifications', {
        method: 'POST',
        headers: {
          Accept: 'application/vnd.onesignal.v1+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          app_id: ONESIGNAL_APP_ID,
          include_subscription_ids: [pushSubscriptionId],
          headings: { en: 'OneSignal No-Location Demo' },
          contents: { en: 'This test push was sent without linking the location module.' },
        }),
      });

      if (!response.ok) {
        const message = await response.text();
        window.alert(`Send Failed\n\n${message}`);
      }
    } catch (error) {
      window.alert(`Send Failed\n\n${String(error)}`);
    } finally {
      setSending(false);
    }
  }, [permission, pushSubscriptionId]);

  return (
    <main className="app">
      <header className="appbar">
        <div className="appbar-content">
          <h1>OneSignal</h1>
          <p>No-Location Demo</p>
        </div>
      </header>

      <div className="content">
        <section className="section">
          <h2>App</h2>
          <div className="card">
            <dl>
              <div>
                <dt>App ID</dt>
                <dd className={isPlaceholder(ONESIGNAL_APP_ID) ? 'warning' : undefined}>
                  {ONESIGNAL_APP_ID}
                </dd>
              </div>
            </dl>
          </div>
        </section>

        <section className="section">
          <h2>Push</h2>
          <div className="card">
            <dl>
              <div>
                <dt>Permission</dt>
                <dd>{permission == null ? 'Unknown' : permission ? 'Granted' : 'Not granted'}</dd>
              </div>
              <div>
                <dt>Push ID</dt>
                <dd>{pushSubscriptionId || '-'}</dd>
              </div>
            </dl>
            <button type="button" onClick={requestPermission} disabled={requestingPermission}>
              REQUEST PERMISSION
            </button>
            <div className="button-spacer" />
            <button type="button" onClick={sendTestNotification} disabled={sending}>
              SEND TEST NOTIFICATION
            </button>
          </div>
        </section>

        <section className="section">
          <h2>Location Module</h2>
          <div className="card">
            <p>
              This demo initializes OneSignal and requests notification permission only when you tap
              the button above. Native build flags exclude the location module. The location test
              call may not log a JavaScript error; check Android Logcat or Xcode logs for native
              diagnostics.
            </p>
            <div className="location-button-wrap">
              <button type="button" className="secondary" onClick={testLocationPermissionRequest}>
                TEST LOCATION REQUEST
              </button>
            </div>
          </div>
        </section>
      </div>
    </main>
  );
}

// examples/demo_cap7/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, signal } from '@angular/core';
import { CapacitorHttp } from '@capacitor/core';
import OneSignal, { LogLevel } from '@onesignal/capacitor-plugin';

const ONESIGNAL_APP_ID = '77e32082-ea27-42e3-a898-c72e141824ef';

@Component({
  selector: 'app-root',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h1>OneSignal Capacitor 7 Demo</h1>
    <p class="subtitle">Hello-world for verifying the OneSignal plugin on Capacitor 7.</p>

    <button type="button" (click)="initialize()">1. Initialize OneSignal</button>
    <button type="button" [disabled]="!initialized()" (click)="requestPermission()">
      2. Request Notification Permission
    </button>
    <button type="button" [disabled]="!initialized()" (click)="showSubscriptionInfo()">
      3. Show OneSignal ID (send a test push to it)
    </button>
    <button type="button" [disabled]="!initialized() || sending()" (click)="sendTestNotification()">
      4. Send Test Notification
    </button>

    <pre>{{ logText() }}</pre>
  `,
})
export class AppComponent {
  protected readonly initialized = signal(false);
  protected readonly sending = signal(false);
  protected readonly logText = signal('Ready. Tap "Initialize OneSignal" to start.');

  protected initialize(): void {
    if (this.initialized()) {
      this.log('Already initialized.');
      return;
    }
    OneSignal.Debug.setLogLevel(LogLevel.Verbose);
    void OneSignal.initialize(ONESIGNAL_APP_ID);

    OneSignal.Notifications.addEventListener('foregroundWillDisplay', (event) => {
      const n = event.getNotification();
      this.log(`foregroundWillDisplay: ${n.title ?? '(no title)'}`);
    });

    this.initialized.set(true);
    this.log(`OneSignal initialized with app id ${ONESIGNAL_APP_ID}`);
  }

  protected async requestPermission(): Promise<void> {
    try {
      const accepted = await OneSignal.Notifications.requestPermission(true);
      this.log(`Permission accepted: ${String(accepted)}`);
    } catch (err) {
      this.log(`requestPermission error: ${String(err)}`);
    }
  }

  protected async showSubscriptionInfo(): Promise<void> {
    try {
      const [onesignalId, subscriptionId, optedIn, hasPerm] = await Promise.all([
        OneSignal.User.getOnesignalId(),
        OneSignal.User.pushSubscription.getIdAsync(),
        OneSignal.User.pushSubscription.getOptedInAsync(),
        OneSignal.Notifications.hasPermission(),
      ]);
      this.log(
        [
          `OneSignal user id:    ${onesignalId ?? '(none)'}`,
          `Push subscription id: ${subscriptionId ?? '(none)'}`,
          `Opted in:             ${String(optedIn)}`,
          `Has permission:       ${String(hasPerm)}`,
          '',
          'Send a test push to the subscription id above',
          'from the OneSignal dashboard to see it appear.',
        ].join('\n'),
      );
    } catch (err) {
      this.log(`showSubscriptionInfo error: ${String(err)}`);
    }
  }

  protected async sendTestNotification(): Promise<void> {
    this.sending.set(true);
    try {
      const subscriptionId = await OneSignal.User.pushSubscription.getIdAsync();
      if (!subscriptionId) {
        this.log('No push subscription id yet. Grant permission first.');
        return;
      }

      const response = await CapacitorHttp.post({
        url: 'https://onesignal.com/api/v1/notifications',
        headers: {
          Accept: 'application/vnd.onesignal.v1+json',
          'Content-Type': 'application/json',
        },
        data: {
          app_id: ONESIGNAL_APP_ID,
          include_subscription_ids: [subscriptionId],
          headings: { en: 'Simple Notification' },
          contents: { en: 'This is a simple push notification' },
        },
      });

      if (response.status < 200 || response.status >= 300) {
        this.log(`Send failed (${response.status}): ${JSON.stringify(response.data)}`);
        return;
      }

      this.log(`Sent. response: ${JSON.stringify(response.data)}`);
    } catch (err) {
      this.log(`sendTestNotification error: ${String(err)}`);
    } finally {
      this.sending.set(false);
    }
  }

  private log(message: string): void {
    const stamp = new Date().toISOString().slice(11, 19);
    this.logText.update((prev) => `[${stamp}] ${message}\n${prev}`);
    console.log(`[demo-cap7] ${message}`);
  }
}
